version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  toolbox:
    build: .
    container_name: cybertoolbox
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - zap-data:/root/.ZAP
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: toolbox
      DB_USER: admin
      DB_PASSWORD: admin

  db:
    image: postgres:14
    container_name: toolbox_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: toolbox
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  zap-data:
  pgdata:
